# Generated by Django 4.2.10 on 2024-03-04 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchInfo",
            fields=[
                ("matchID", models.IntegerField(primary_key=True, serialize=False)),
                ("matchdate", models.DateField(null=True)),
                ("matchtime", models.TimeField(default="19:30:00", null=True)),
                ("status", models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="PlayerInfo",
            fields=[
                ("playerID", models.IntegerField(primary_key=True, serialize=False)),
                ("playerName", models.CharField(max_length=24, null=True)),
                ("playerRole", models.SmallIntegerField(null=True)),
                ("playing11status", models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name="TeamInfo",
            fields=[
                ("teamID", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("teamname", models.CharField(max_length=30, null=True)),
                ("teamshortform", models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserInfo",
            fields=[
                ("userID", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=24, unique=True)),
                ("name", models.CharField(max_length=24)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_on", models.DateTimeField(null=True)),
                ("score1", models.IntegerField(default=0, null=True)),
                ("score2", models.IntegerField(default=0, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SubmissionsInfo5",
            fields=[
                ("submissionID", models.AutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=24, null=True)),
                ("updated_time", models.DateTimeField(null=True)),
                ("score", models.IntegerField(default=0)),
                (
                    "predictedmr",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicted_mr",
                        to="ipl2.playerinfo",
                    ),
                ),
                (
                    "predictedmwk",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicted_mwk",
                        to="ipl2.playerinfo",
                    ),
                ),
                (
                    "predictedpom",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicted_pom",
                        to="ipl2.playerinfo",
                    ),
                ),
                (
                    "predictedteam",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipl2.teaminfo",
                    ),
                ),
                (
                    "smatch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ipl2.matchinfo"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipl2.userinfo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="playerinfo",
            name="playerTeamNo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_teams",
                to="ipl2.teaminfo",
            ),
        ),
        migrations.AddField(
            model_name="matchinfo",
            name="mostrunsplayer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="most_runs_player",
                to="ipl2.playerinfo",
            ),
        ),
        migrations.AddField(
            model_name="matchinfo",
            name="mostwickettaker",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="most_wickets_taker",
                to="ipl2.playerinfo",
            ),
        ),
        migrations.AddField(
            model_name="matchinfo",
            name="playerofmatch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="player_of_match",
                to="ipl2.playerinfo",
            ),
        ),
        migrations.AddField(
            model_name="matchinfo",
            name="teamA",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teamA_matches",
                to="ipl2.teaminfo",
            ),
        ),
        migrations.AddField(
            model_name="matchinfo",
            name="teamB",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teamB_matches",
                to="ipl2.teaminfo",
            ),
        ),
        migrations.AddField(
            model_name="matchinfo",
            name="winner_team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="winning_matches",
                to="ipl2.teaminfo",
            ),
        ),
        migrations.CreateModel(
            name="LbRegistrationTable",
            fields=[
                ("lid", models.AutoField(primary_key=True, serialize=False)),
                ("leaderboardname", models.CharField(max_length=30)),
                ("password", models.CharField(max_length=16)),
                (
                    "uid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ipl2.userinfo"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LbParticipationTable",
            fields=[
                ("lpid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "lid",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ipl2.lbregistrationtable",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participations",
                        to="ipl2.userinfo",
                    ),
                ),
            ],
        ),
    ]
