# Generated by Django 4.2.10 on 2024-03-06 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ipl2", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="matchinfo",
            name="location",
            field=models.CharField(default="Chinnaswamy", max_length=48),
        ),
    ]
